"use strict";

const path = require("path");
const fs = require("fs");
const { chromium } = require("playwright");

/**
 * Generate a styled PDF report using Playwright (headless Chromium).
 * @param {object} opts
 * @param {string} opts.title - Report title
 * @param {string} opts.content - Main report body (markdown-ish text)
 * @param {string} [opts.outputPath] - Where to save the PDF (default: ./data/colwork_report.pdf)
 * @returns {Promise<string>} - Path to the generated PDF
 */
async function generatePDF({ title, content, outputPath }) {
  const pdfPath = outputPath || path.resolve(process.cwd(), "data", "colwork_report.pdf");
  const dir = path.dirname(pdfPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const html = buildReportHTML(title, content);

  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: "networkidle" });
  await page.pdf({
    path: pdfPath,
    format: "A4",
    margin: { top: "40px", bottom: "40px", left: "40px", right: "40px" },
    printBackground: true,
  });
  await browser.close();

  console.log(`[reporting] PDF generated: ${pdfPath}`);
  return pdfPath;
}

function buildReportHTML(title, content) {
  const date = new Date().toLocaleDateString("pl-PL", {
    year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit",
  });

  // Convert content newlines to <p>/<br> structure
  const bodyHTML = content
    .split("\n")
    .map((line) => {
      const trimmed = line.trim();
      if (!trimmed) return "<br/>";
      if (trimmed.startsWith("# ")) return `<h2>${escapeHTML(trimmed.slice(2))}</h2>`;
      if (trimmed.startsWith("- ")) return `<li>${escapeHTML(trimmed.slice(2))}</li>`;
      return `<p>${escapeHTML(trimmed)}</p>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="UTF-8">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'JetBrains Mono', monospace; color: #e0e0e0; background: #0a0a0a; padding: 32px; }
    .header { border-bottom: 2px solid #00bcd4; padding-bottom: 16px; margin-bottom: 24px; }
    .title { font-size: 24px; font-weight: 700; color: #00bcd4; letter-spacing: 2px; }
    .subtitle { font-size: 11px; color: #666; margin-top: 4px; }
    .content { font-size: 12px; line-height: 1.8; }
    .content h2 { color: #00bcd4; font-size: 14px; margin: 20px 0 8px 0; }
    .content p { margin: 6px 0; }
    .content li { margin: 3px 0 3px 20px; }
    .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #333; font-size: 9px; color: #555; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <div class="title">COLWORK</div>
    <div class="subtitle">Autonomous Career Intelligence Report | ${date}</div>
  </div>
  <div class="content">
    ${bodyHTML}
  </div>
  <div class="footer">
    Generated by CoLwork — open-source autonomous career engine<br/>
    DeepSeek • Kimi • Playwright Stealth<br/>
    https://github.com/${process.env.GITHUB_OWNER || "your-org"}/colwork
  </div>
</body>
</html>`;
}

function escapeHTML(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Send a PDF report via email using nodemailer.
 * SMTP credentials are read from .env:
 *   SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS
 * @param {string} pdfPath - Path to the PDF file
 * @param {string} recipient - Email address to send to
 * @returns {Promise<boolean>}
 */
async function sendEmail(pdfPath, recipient) {
  const nodemailer = require("nodemailer");

  const host = process.env.SMTP_HOST;
  const port = parseInt(process.env.SMTP_PORT || "587", 10);
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (!host || !user || !pass) {
    console.warn("[reporting] SMTP not configured in .env. Skipping email.");
    console.warn("[reporting] Add: SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS");
    return false;
  }

  const transporter = nodemailer.createTransport({
    host,
    port,
    secure: port === 465,
    auth: { user, pass },
  });

  const filename = path.basename(pdfPath);

  await transporter.sendMail({
    from: `"Colwork Agent" <${user}>`,
    to: recipient,
    subject: `Colwork Report — ${new Date().toLocaleDateString("pl-PL")}`,
    text: "W załączniku znajduje się wygenerowany raport Colwork.",
    attachments: [{ filename, path: pdfPath }],
  });

  console.log(`[reporting] Email sent to ${recipient} with ${filename}`);
  return true;
}

module.exports = { generatePDF, sendEmail };
