import React, { useState, useEffect } from "react";
import { Sparkles, Key, Wifi, Loader2, CheckCircle2 } from "lucide-react";

const ipc = typeof window !== "undefined" ? window.colwork : null;

export default function OnboardingModal({ onDone }) {
  const [deepseekKey, setDeepseekKey] = useState("");
  const [n8nUrl, setN8nUrl] = useState("");
  const [saving, setSaving] = useState(false);
  const [done, setDone] = useState(false);
  const [error, setError] = useState(null);
  const [envPath, setEnvPath] = useState("");

  useEffect(() => {
    if (!ipc) return;
    ipc.engine.getSetupStatus().then((s) => {
      if (s?.envPath) setEnvPath(s.envPath);
    }).catch(() => {});
  }, []);

  const save = async () => {
    if (!deepseekKey.trim() && !n8nUrl.trim()) return;
    setSaving(true);
    setError(null);
    try {
      const lines = [];
      lines.push("# CoLwork environment — generated by onboarding wizard");
      lines.push("");
      if (deepseekKey.trim()) {
        lines.push(`DEEPSEEK_API_KEY=${deepseekKey.trim()}`);
        lines.push("DEEPSEEK_MODEL=deepseek-chat");
        lines.push("DEEPSEEK_BASE_URL=https://api.deepseek.com/v1");
      }
      if (n8nUrl.trim()) {
        lines.push(`N8N_BASE_URL=${n8nUrl.trim()}`);
        lines.push("N8N_API_KEY=");
      }
      lines.push("");
      const content = lines.join("\n");
      const res = await ipc.engine.saveEnv(content);
      if (!res?.ok) throw new Error(res?.error || "Failed to save");
      setDone(true);
      setTimeout(() => onDone?.(), 1200);
    } catch (e) {
      setError(e.message || "Save failed — write the .env manually for now.");
    } finally {
      setSaving(false);
    }
  };

  if (done) {
    return (
      <div className="fixed inset-0 z-[100] flex items-center justify-center bg-zinc-950/80 backdrop-blur-sm">
        <div className="bg-zinc-900 border border-green-500/30 rounded-xl p-8 text-center shadow-2xl max-w-sm w-full">
          <CheckCircle2 size={40} className="text-green-400 mx-auto mb-3" strokeWidth={1.5} />
          <h3 className="text-lg font-bold text-green-300">Engine armed</h3>
          <p className="text-xs text-zinc-400 mt-2">MoE board is now online. Dashboard refreshing…</p>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-zinc-950/80 backdrop-blur-sm p-4">
      <div className="bg-zinc-900 border border-zinc-700/60 rounded-xl p-6 shadow-2xl max-w-md w-full backdrop-blur-sm animate-slide-in space-y-5">
        <div className="text-center">
          <Sparkles size={28} className="text-linkedin-light mx-auto mb-2" strokeWidth={1.5} />
          <h2 className="text-lg font-bold text-white">Welcome to CoLwork</h2>
          <p className="text-xs text-zinc-400 mt-1.5 leading-relaxed">
            To activate the <span className="text-linkedin-light">Mixture-of-Experts board</span>, we need your API keys.
            <br />
            <span className="text-zinc-600">
              Stored in <code className="text-zinc-500">{envPath || "%APPDATA%/CoLwork/.env"}</code>
            </span>
          </p>
        </div>

        <div className="space-y-3">
          <label className="block">
            <span className="text-[11px] text-zinc-400 font-mono uppercase flex items-center gap-1.5 mb-1">
              <Key size={11} className="text-linkedin-light" /> DeepSeek API Key
            </span>
            <input
              type="password"
              value={deepseekKey}
              onChange={(e) => setDeepseekKey(e.target.value)}
              placeholder="sk-..."
              className="w-full bg-zinc-950 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-zinc-100 placeholder-zinc-600 focus:border-linkedin focus:ring-1 focus:ring-linkedin/30 outline-none transition font-mono"
            />
          </label>

          <label className="block">
            <span className="text-[11px] text-zinc-400 font-mono uppercase flex items-center gap-1.5 mb-1">
              <Wifi size={11} className="text-linkedin-light" /> n8n Webhook URL
            </span>
            <input
              type="url"
              value={n8nUrl}
              onChange={(e) => setN8nUrl(e.target.value)}
              placeholder="https://your-n8n.example.com/api/v1"
              className="w-full bg-zinc-950 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-zinc-100 placeholder-zinc-600 focus:border-linkedin focus:ring-1 focus:ring-linkedin/30 outline-none transition font-mono"
            />
          </label>
        </div>

        {error && (
          <p className="text-xs text-red-400 bg-red-500/5 border border-red-500/20 rounded-lg p-2.5">{error}</p>
        )}

        <button
          onClick={save}
          disabled={saving || (!deepseekKey.trim() && !n8nUrl.trim())}
          className="w-full bg-linkedin hover:bg-linkedin-dark disabled:bg-zinc-800 disabled:text-zinc-600 disabled:cursor-not-allowed text-white font-semibold py-2.5 rounded-lg transition-all flex items-center justify-center gap-2 shadow-lg shadow-linkedin/10"
        >
          {saving ? (
            <><Loader2 size={16} className="animate-spin" /> Saving…</>
          ) : (
            "Arm the MoE Board"
          )}
        </button>

        <button
          onClick={() => onDone?.()}
          className="w-full text-xs text-zinc-600 hover:text-zinc-400 transition"
        >
          Skip for now
        </button>
      </div>
    </div>
  );
}
